### ISSUE TITLE
`npm run build` explodes

### ISSUE THREAD

**Issue by astra137** [multi-cell/devise-ante#39]
Something with source maps is buggered and I cannot build *feat/tags* on Windows. Do you want me to look into this?

**Comment by puregarlic** [comment]
Nah, I'll see what I can do

**Comment by puregarlic** [comment]
@maccelerated, what are your steps to reproduce? I checked out the branch, installed dependencies, and ran `yarn build` and everything worked fine, no problems.

**Comment by puregarlic** [comment]
Double-checked with `npm run build`, same thing.

**Comment by astra137** [comment]
I'll try again. Could have been something specific about the env.

**Comment by astra137** [comment]
Happens with latest feat/tags on macOS as well. I even `rm -rf`'d node_modules to make sure. `Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.`

**Comment by puregarlic** [comment]
Looks like something similar is happening here: https://github.com/mozilla/source-map/issues/304
